//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Google_Api.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public Addresses()
        {
            this.Recensio = new HashSet<Recensio>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public Nullable<double> longtitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public int restaurantID { get; set; }
        public Nullable<int> imageId { get; set; }
        public int districtId { get; set; }
    
        public virtual Districts Districts { get; set; }
        public virtual Images Images { get; set; }
        public virtual Restaurants Restaurants { get; set; }
        public virtual ICollection<Recensio> Recensio { get; set; }
    }
}
