//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Google_Api.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities
    {
        public cities()
        {
            this.districts = new HashSet<districts>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<districts> districts { get; set; }
    }
}
