//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Google_Api.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomLabels
    {
        public int id { get; set; }
        public int recensioID { get; set; }
        public string customLabel { get; set; }
        public System.DateTime dateOfCreation { get; set; }
    
        public virtual Recensio Recensio { get; set; }
    }
}
