//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Google_Api.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class networks
    {
        public networks()
        {
            this.restaurants = new HashSet<restaurants>();
        }
    
        public int Id { get; set; }
        public string Network { get; set; }
    
        public virtual ICollection<restaurants> restaurants { get; set; }
    }
}
