//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Google_Api.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurants_dbEntities : DbContext
    {
        public restaurants_dbEntities()
            : base("name=restaurants_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<districts> districts { get; set; }
        public virtual DbSet<networks> networks { get; set; }
        public virtual DbSet<restaurants> restaurants { get; set; }
        public virtual DbSet<usercomments> usercomments { get; set; }
    }
}
