//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Google_Api.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantsDBEntities : DbContext
    {
        public RestaurantsDBEntities()
            : base("name=RestaurantsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<Cities> Cities { get; set; }
        //public virtual DbSet<Districts> Districts { get; set; }
        //public virtual DbSet<Networks> Networks { get; set; }
        //public virtual DbSet<Restaurants> Restaurants { get; set; }
        //public virtual DbSet<UserComments> UserComments { get; set; }
    }
}
